### ISSUE TITLE
Rename setup-Ubuntu1804.yml to setup-Debian.yml

### ISSUE THREAD

**Issue by jasonwalsh** [mongodb-ansible-roles/ansible-role-faketime#4]
I think we should rename `setup-Ubuntu1804.yml` to `setup-Debian.yml`. The only task in the file is:

```yaml
- apt:
    name: faketime
    state: present
```

Since all Debian-based distributions use APT, it is unnecessary to include the release version in the filename.

Renaming the file will also prevent adding extra conditionals for the `include_tasks` directive in `main.yml`.
